/**
 * 校园机会板 —— 考核材料数据层
 *
 * 数据全部来自《计算机协会软件部 2026 年秋季纳新第二轮考核题目》第四部分的
 * 26 条模拟信息。原则：
 *   1. 只搬运材料里写了的字段，材料没写的留空并标注「未提供」；
 *   2. 不做任何推测性补全（不给未公布的活动编日期、编地点、编主办方）；
 *   3. 材料内部的矛盾（如「9月20日为周日却写每周六」）当作待用户确认项呈现，
 *      而不是由产品偷偷改掉。
 *
 * 字段说明：
 *   source.kind  official 学校/部门 | college 学院 | student 学生个人发布 | unknown 主办方未标注
 *   trust        high 官方发布 | medium 学生发布且信息完整 | low 存在推广/缺项风险
 *   updateOf     本条是某条信息的补充通知（用于合并成一条时间线）
 */

// 题目要求以 2026 年 9 月 19 日为时间背景，考核当天 14:00 开始。
// 全站所有「还剩多久 / 是否已结束」都以这个基准时刻推算，保证可复现。
const REFERENCE_NOW = "2026-09-19T14:00:00+08:00";

const RAW_ITEMS = [
  {
    id: "01",
    title: "“蓝桥杯”程序设计校内训练营",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "竞赛训练",
    audience: "全校学生",
    summary: "9月24日22:00报名截止；原计划9月20日起每周六19:00训练；零基础可参加。",
    eventStart: "2026-09-20T19:00",
    eventStartNote: "原计划",
    eventEnd: null,
    location: null,
    locationNote: "待最新通知确认",
    deadline: "2026-09-24T22:00",
    deadlineNote: null,
    cost: null,
    capacity: null,
    requirements: ["零基础可参加", "材料未注明报名方式"],
    tags: ["零基础", "每周训练"],
    flags: [],
  },
  {
    id: "02",
    title: "AI应用入门公开课",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "公开课",
    audience: "全校学生",
    summary: "9月19日19:00；计算机学院教学楼；无需报名；预计90分钟。",
    eventStart: "2026-09-19T19:00",
    eventStartNote: null,
    eventEnd: "2026-09-19T20:30",
    location: "计算机学院教学楼",
    locationNote: "具体教室未注明",
    deadline: null,
    deadlineNote: "无需报名",
    cost: null,
    capacity: null,
    requirements: ["无需报名"],
    tags: ["今晚", "免费"],
    flags: [],
  },
  {
    id: "03",
    title: "大学生创新创业项目团队招募",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "团队招募",
    audience: "全校学生",
    summary: "招募开发、设计、材料成员；每周需稳定投入4小时以上；9月22日18:00截止；需提交简短自我介绍。",
    eventStart: null,
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: "2026-09-22T18:00",
    deadlineNote: null,
    cost: null,
    capacity: null,
    requirements: ["每周稳定投入4小时以上", "需提交简短自我介绍"],
    tags: ["长期项目", "三个方向"],
    flags: [],
  },
  {
    id: "04",
    title: "数学建模竞赛经验分享会",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "分享会",
    audience: "不限专业",
    summary: "直播时间为9月18日19:30；不限专业；直播已结束，活动方预计9月20日上传回放。",
    statedStatus: "ended",
    eventStart: "2026-09-18T19:30",
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "直播，线上",
    deadline: null,
    deadlineNote: null,
    cost: null,
    capacity: null,
    requirements: [],
    tags: ["已结束", "有回放"],
    flags: [{ level: "info", text: "回放为「预计9月20日上传」，尚未确认是否已上线" }],
  },
  {
    id: "05",
    title: "校园公益志愿服务活动",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "志愿服务",
    audience: "全校学生",
    summary: "活动时间9月27日8:30—17:00；9月20日12:00报名截止；预计服务8小时；需提前到场签到。",
    eventStart: "2026-09-27T08:30",
    eventStartNote: null,
    eventEnd: "2026-09-27T17:00",
    location: null,
    locationNote: "未提供",
    deadline: "2026-09-20T12:00",
    deadlineNote: null,
    cost: null,
    capacity: null,
    requirements: ["需提前到场签到"],
    tags: ["志愿时长", "一天"],
    flags: [],
  },
  {
    id: "06",
    title: "Web开发零基础学习小组",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "学习小组",
    audience: "零基础学生",
    summary: "9月23日起每周三19:30开展，共6周；面向零基础学生；限30人；报名时间未注明，满员即止。",
    eventStart: "2026-09-23T19:30",
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: null,
    deadlineNote: "报名时间未注明，满员即止",
    cost: null,
    capacity: "限30人",
    requirements: ["共6周，每周三19:30"],
    tags: ["零基础", "6周", "限额"],
    flags: [{ level: "warn", text: "没有报名截止时间，满员即止，建议尽早确认名额" }],
  },
  {
    id: "07",
    title: "AI创新应用挑战赛",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "竞赛",
    audience: "全校学生",
    summary: "2—4人组队；9月21日18:00前完成校内意向登记；10月20日提交作品；意向登记不等同于最终作品提交。",
    eventStart: null,
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: "2026-09-21T18:00",
    deadlineNote: "校内意向登记截止；作品提交为10月20日",
    cost: null,
    capacity: "2—4人组队",
    requirements: ["意向登记不等于最终报名", "10月20日提交作品"],
    tags: ["组队", "两级截止"],
    flags: [],
  },
  {
    id: "08",
    title: "校园软件项目组招募",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "团队招募",
    audience: "大一、大二学生",
    summary: "开发校园实用工具；面向大一、大二学生；希望成员了解Git基本操作；每周预计投入5小时；长期招募，满员即止。",
    eventStart: null,
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: null,
    deadlineNote: "长期招募，满员即止",
    cost: null,
    capacity: null,
    requirements: ["希望了解Git基本操作", "每周预计投入5小时"],
    tags: ["长期", "仅大一/大二"],
    flags: [],
  },
  {
    id: "09",
    title: "程序设计训练营补充通知",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "补充通知",
    audience: "全校学生",
    summary: "因场地调整，首次训练改为9月21日19:30，地点改至实验楼A402；已报名同学无需重复提交；报名截止时间不变。",
    eventStart: "2026-09-21T19:30",
    eventStartNote: null,
    eventEnd: null,
    location: "实验楼A402",
    locationNote: null,
    deadline: null,
    deadlineNote: "报名截止时间不变（仍为9月24日22:00）",
    cost: null,
    capacity: null,
    requirements: ["已报名同学无需重复提交"],
    tags: ["场地变更", "时间变更"],
    flags: [],
    updateOf: "01",
  },
  {
    id: "10",
    title: "前端开发经验交流会",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "分享会",
    audience: "全校学生",
    summary: "9月19日15:00—16:30；线下A201并同步线上直播；无需报名。",
    eventStart: "2026-09-19T15:00",
    eventStartNote: null,
    eventEnd: "2026-09-19T16:30",
    location: "A201",
    locationNote: "可线上直播",
    deadline: null,
    deadlineNote: "无需报名",
    cost: null,
    capacity: null,
    requirements: ["无需报名"],
    tags: ["一小时后开始", "可线上"],
    flags: [],
  },
  {
    id: "11",
    title: "大学生科研入门分享会",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "分享会",
    audience: "全校学生",
    summary: "9月21日19:00—20:30；介绍论文检索、学生科研项目和导师联系方法。",
    eventStart: "2026-09-21T19:00",
    eventStartNote: null,
    eventEnd: "2026-09-21T20:30",
    location: null,
    locationNote: "未提供",
    deadline: null,
    deadlineNote: null,
    cost: null,
    capacity: null,
    requirements: [],
    tags: ["科研入门"],
    flags: [{ level: "info", text: "材料未注明地点与是否需要报名" }],
  },
  {
    id: "12",
    title: "全国高校计算机能力挑战赛",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "竞赛",
    audience: "本科生",
    summary: "面向本科生；10月5日23:59报名截止；个人参赛；具体费用信息未提供。",
    eventStart: null,
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: "2026-10-05T23:59",
    deadlineNote: null,
    cost: "未提供",
    capacity: null,
    requirements: ["个人参赛"],
    tags: ["个人赛"],
    flags: [{ level: "warn", text: "费用信息未提供，报名前需要先确认是否收费" }],
  },
  {
    id: "13",
    title: "科研助理招募",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "科研招募",
    audience: "大二及以上",
    summary: "协助数据整理和实验工作；仅限大二及以上学生；每周预计投入6小时；9月21日截止报名。",
    eventStart: null,
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: "2026-09-21T23:59",
    deadlineNote: "材料只写「9月21日截止」，未注明具体时刻",
    cost: null,
    capacity: null,
    requirements: ["仅限大二及以上", "每周预计投入6小时"],
    tags: ["有年级限制"],
    flags: [{ level: "info", text: "截止时间只精确到日期，当天几点截止需再确认" }],
  },
  {
    id: "14",
    title: "Git与GitHub零基础工作坊",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "工作坊",
    audience: "主要面向大一新生",
    summary: "9月21日19:00—20:30；主要面向大一新生；限40人；需提前预约，提交报名表不代表最终录取，以审核通知为准。",
    eventStart: "2026-09-21T19:00",
    eventStartNote: null,
    eventEnd: "2026-09-21T20:30",
    location: null,
    locationNote: "未提供",
    deadline: null,
    deadlineNote: "需提前预约，截止时间未注明",
    cost: null,
    capacity: "限40人",
    requirements: ["提交报名表不等于录取", "以审核通知为准"],
    tags: ["零基础", "限额", "需审核"],
    flags: [{ level: "warn", text: "报名表不代表录取，提交后要留意审核通知" }],
  },
  {
    id: "15",
    title: "AI应用创意挑战",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "竞赛",
    audience: "全校学生",
    summary: "9月23日23:59前提交创意方案；9月30日前提交最终作品；允许个人或团队参加；进入展示环节后可再组队。",
    eventStart: null,
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: "2026-09-23T23:59",
    deadlineNote: "最终作品提交为9月30日前",
    cost: null,
    capacity: "个人或团队",
    requirements: ["先交创意方案，再交最终作品"],
    tags: ["两级提交", "可个人"],
    flags: [],
  },
  {
    id: "16",
    title: "校园摄影志愿者招募",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "志愿者招募",
    audience: "全校学生",
    summary: "长期招募；参与校内大型活动摄影；具体报名截止时间未注明；有摄影设备者优先但不作硬性要求。",
    eventStart: null,
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: null,
    deadlineNote: "具体报名截止时间未注明",
    cost: null,
    capacity: null,
    requirements: ["有摄影设备者优先，非硬性要求"],
    tags: ["长期招募", "设备优先"],
    flags: [{ level: "info", text: "没有截止时间，适合长期关注，但不适合当作紧急事项" }],
  },
  {
    id: "17",
    title: "Python程序设计学习资料合集",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "学习资料",
    audience: "全校学生",
    summary: "包含课程、练习和项目案例；资料长期开放；当前网盘提取信息有效至9月22日，后续将统一更新。",
    eventStart: null,
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "网盘资料",
    deadline: "2026-09-22T23:59",
    deadlineNote: "指当前网盘提取信息有效期，资料本身长期开放",
    cost: null,
    capacity: null,
    requirements: [],
    tags: ["资料", "有失效时间"],
    flags: [{ level: "warn", text: "网盘提取信息9月22日后失效，需要在此之前保存" }],
  },
  {
    id: "18",
    title: "网络安全兴趣交流小组",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "兴趣小组",
    audience: "不限基础",
    summary: "首次交流时间为9月19日19:30；之后每两周开展一次；面向CTF、Web安全等方向感兴趣的学生。",
    eventStart: "2026-09-19T19:30",
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: null,
    deadlineNote: null,
    cost: null,
    capacity: null,
    requirements: [],
    tags: ["今晚", "每两周"],
    flags: [{ level: "info", text: "只公布了首次时间和「每两周一次」，后续具体日期未给出，不做推算" }],
  },
  {
    id: "19",
    title: "学生创新项目路演观摩",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "观摩活动",
    audience: "全校学生",
    summary: "活动时间9月20日14:30；原报名截止时间为9月18日22:00；活动方说明如现场仍有余位，可接受候补入场。",
    eventStart: "2026-09-20T14:30",
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: "2026-09-18T22:00",
    deadlineNote: "已过期；现场如有余位可候补",
    cost: null,
    capacity: null,
    requirements: ["候补入场取决于现场余位"],
    tags: ["报名已截止", "可候补"],
    flags: [{ level: "info", text: "报名通道已关闭，只能到现场看是否有余位" }],
  },
  {
    id: "20",
    title: "创新创业项目团队补充说明",
    source: { kind: "unknown", name: "主办方未标注" },
    trust: "medium",
    type: "补充通知",
    audience: "全校学生",
    summary: "开发方向名额已满，现主要补充设计与材料成员；9月22日18:00截止；此前已投递者无需重复提交。",
    eventStart: null,
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: "2026-09-22T18:00",
    deadlineNote: null,
    cost: null,
    capacity: "开发方向已满",
    requirements: ["此前已投递者无需重复提交"],
    tags: ["名额变化", "开发已满"],
    flags: [],
    updateOf: "03",
  },
  {
    id: "21",
    title: "计算机学院AI产品设计分享会",
    source: { kind: "college", name: "计算机学院" },
    trust: "high",
    type: "分享会",
    audience: "全校学生",
    summary: "计算机学院发布；9月20日19:00；明德楼B203；无需报名，座位有限。",
    eventStart: "2026-09-20T19:00",
    eventStartNote: null,
    eventEnd: null,
    location: "明德楼B203",
    locationNote: null,
    deadline: null,
    deadlineNote: "无需报名",
    cost: null,
    capacity: "座位有限",
    requirements: ["无需报名，先到先得"],
    tags: ["学院发布", "明晚"],
    flags: [],
  },
  {
    id: "22",
    title: "周末羽毛球约球",
    source: { kind: "student", name: "学生个人发布" },
    trust: "medium",
    type: "约球",
    audience: "不限",
    summary: "学生个人发布；9月20日16:00；计划6—8人；费用AA；场地待最终确认。",
    eventStart: "2026-09-20T16:00",
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "场地待最终确认",
    deadline: null,
    deadlineNote: "未注明报名截止",
    cost: "AA",
    capacity: "6—8人",
    requirements: ["费用AA", "场地未定"],
    tags: ["学生发起", "AA"],
    flags: [{ level: "warn", text: "场地尚未确认，出发前必须先问清楚地点" }],
  },
  {
    id: "23",
    title: "AI工具交流搭子招募",
    source: { kind: "student", name: "学生个人发布" },
    trust: "medium",
    type: "兴趣交流",
    audience: "欢迎零基础",
    summary: "学生个人发布；拟于9月21日晚开展；欢迎零基础；报名后拉群；具体地点未确定。",
    eventStart: "2026-09-21T19:00",
    eventStartNote: "材料只写「晚间」，此处按晚间示意，具体时间未定",
    eventEnd: null,
    location: null,
    locationNote: "具体地点未确定",
    deadline: null,
    deadlineNote: "未注明报名截止",
    cost: null,
    capacity: null,
    requirements: ["报名后拉群"],
    tags: ["学生发起", "零基础"],
    flags: [{ level: "warn", text: "时间和地点都还没定，只说到「晚间」和「地点未确定」" }],
  },
  {
    id: "24",
    title: "“校园兼职福利分享”",
    source: { kind: "student", name: "学生个人发布" },
    trust: "low",
    type: "兼职信息",
    audience: "未说明",
    summary: "称“零门槛、日结”，要求添加私人微信获取详情；未提供主办方、地点和完整内容。",
    eventStart: null,
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未提供",
    deadline: null,
    deadlineNote: "未提供",
    cost: null,
    capacity: null,
    requirements: ["需添加私人微信"],
    tags: ["学生发起", "待核实"],
    flags: [
      { level: "danger", text: "「零门槛、日结」且要求加私人微信，无主办方、无地点，存在风险" },
      { level: "info", text: "平台不提供担保，涉及转账、押金、身份证信息时请谨慎" },
    ],
  },
  {
    id: "25",
    title: "数码新品体验交流",
    source: { kind: "student", name: "学生个人发布" },
    trust: "low",
    type: "兴趣交流",
    audience: "未说明",
    summary: "学生个人发布；标题为技术交流，正文主要介绍某商家优惠及购买链接；活动时间、地点未注明。",
    eventStart: null,
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "未注明",
    deadline: null,
    deadlineNote: "未注明",
    cost: null,
    capacity: null,
    requirements: ["附有购买链接"],
    tags: ["学生发起", "疑似推广"],
    flags: [
      { level: "danger", text: "标题写技术交流，正文是商家优惠和购买链接，属于推广内容" },
      { level: "info", text: "没有活动时间与地点，实际上不构成一场校园活动" },
    ],
  },
  {
    id: "26",
    title: "外国语学院校园语言角",
    source: { kind: "college", name: "外国语学院" },
    trust: "high",
    type: "交流活动",
    audience: "全校学生",
    summary: "外国语学院发布；9月21日15:00；面向全校学生；自由交流；场地容量有限，无需提前报名。",
    eventStart: "2026-09-21T15:00",
    eventStartNote: null,
    eventEnd: null,
    location: null,
    locationNote: "材料未注明场地",
    deadline: null,
    deadlineNote: "无需提前报名",
    cost: null,
    capacity: "场地容量有限",
    requirements: ["自由交流，无需报名"],
    tags: ["学院发布", "无需报名"],
    flags: [{ level: "info", text: "场地容量有限且未注明具体地点，建议提前到场" }],
  },
];
